import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
const Button = ({ children, variant = 'primary', ...props }) => {
    return (_jsx("button", { className: `
        px-4 py-2 rounded-md font-medium transition-colors
        ${variant === 'primary'
            ? 'bg-blue-600 text-white hover:bg-blue-700'
            : 'bg-gray-200 text-gray-700 hover:bg-gray-300'}
      `, ...props, children: children }));
};
function Home() {
    return (_jsx("main", { className: "min-h-screen flex items-center justify-center bg-gray-50", children: _jsxs("div", { className: "w-[90%] max-w-[600px] bg-white rounded-lg shadow-lg p-6", children: [_jsxs("div", { className: "text-center mb-6", children: [_jsx("h1", { className: "text-2xl font-bold mb-2", children: "English Literacy Assessment" }), _jsx("p", { className: "text-gray-600", children: "For CJK Heritage Students in North America" })] }), _jsxs("div", { className: "space-y-6", children: [_jsxs("div", { className: "text-center space-y-2", children: [_jsx("h3", { className: "font-medium", children: "What to Expect:" }), _jsxs("ul", { className: "text-sm text-gray-600", children: [_jsx("li", { children: "15 Questions" }), _jsx("li", { children: "About 20 Minutes" }), _jsx("li", { children: "Reading and Understanding" })] })] }), _jsx("div", { className: "text-center", children: _jsx(Button, { variant: "primary", onClick: () => window.location.href = '/assessment', children: "Start Assessment" }) }), _jsx("p", { className: "text-xs text-center text-gray-500", children: "Your results will help us understand your English literacy level" }), _jsxs("div", { className: "text-center mt-8", children: [_jsx("h3", { className: "font-medium text-lg", children: "Pricing" }), _jsx("p", { className: "text-gray-600 mt-2", children: "Choose the plan that works best for you" }), _jsxs("div", { className: "space-y-4 mt-4", children: [_jsxs("div", { className: "bg-gray-100 p-4 rounded-lg", children: [_jsx("h4", { className: "text-gray-800 font-semibold", children: "Monthly" }), _jsx("p", { className: "text-gray-600", children: "$12 per month" }), _jsx(Button, { variant: "primary", onClick: () => window.location.href = '/subscribe?plan=monthly', children: "Subscribe Monthly" })] }), _jsxs("div", { className: "bg-gray-100 p-4 rounded-lg", children: [_jsx("h4", { className: "text-gray-800 font-semibold", children: "Yearly" }), _jsx("p", { className: "text-gray-600", children: "$60 per year (Save 50%)" }), _jsx(Button, { variant: "secondary", onClick: () => window.location.href = '/subscribe?plan=yearly', children: "Subscribe Yearly" })] })] })] })] })] }) }));
}
export default Home;
